name: redcode
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8
  - ca-certificates
  - freetype
  - jpeg
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libdeflate
  - libffi
  - libgcc-ng
  - libgomp
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - lz4-c
  - ncurses
  - openjpeg
  - openssl
  - pillow
  - pip
  - python=3.10
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - accelerate==1.0.1
      - blinker==1.8.1
      - certifi==2024.2.2
      - evdev==1.7.1
      - flask==3.0.3
      - idna==3.7
      - itsdangerous==2.2.0
      - jiter==0.8.2
      - jsonpickle==3.0.4
      - openai
      - pynput==1.7.7
      - pyparsing==3.1.2
      - pyperclip==1.8.2
      - python-xlib==0.33
      - pyyaml==6.0.1
      - safetensors==0.4.5
      - scapy==2.5.0
      - six==1.16.0
      - typing-extensions==4.11.0
      - werkzeug==3.0.2
      - docker
      - pillow
      - opencv-python
      - anthropic
      - google-generativeai
      - matplotlib
      - portpicker
      - ipykernel
      - pyshine
      - wandb
      - tqdm
      - pandas
      - python-dotenv
      - regex
